queue_rules:
  - name: default
    queue_conditions:
      - label!=work-in-progress
      - "#approved-reviews-by>=1"
      - check-success=test (py310)
      - check-success=test (pep8)
    merge_conditions:
      - check-success=test (py310)
      - check-success=test (pep8)
    merge_method: squash

pull_request_rules:
  - name: dismiss reviews
    actions:
      dismiss_reviews: {}
    conditions: []
  - name: refactored queue action rule
    conditions: []
    actions:
      queue:
